title: Cours Avancé pour le M1 du DMA de l'ENS-Paris, (2026).
description: ""

url: https://faenuccio-teaching.github.io
baseurl: "/M1_ENS_26"
repository: faenuccio-teaching/M1_ENS_26

# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: just-the-docs/just-the-docs
#
plugins:
  - jekyll-remote-theme
  # - jekyll-github-metadata

keep_files:
  - docs
  - docbuild

# Sidebar links
show_downloads: true


# the items below are only used for `OnlyTheDoc`
nav:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: Prérequis Lean et GitHub
    url: /index.html#prerequis-lean-et-github
  - title: GitHub
    url: https://github.com/faenuccio-teaching/M1_ENS_26